"""empty message

Revision ID: f4407802fe39
Revises: 
Create Date: 2019-07-24 17:25:57.169423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4407802fe39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=60), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('pending', 'parsed'), nullable=True),
    sa.Column('parsed_at', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_session_id'), 'links', ['session_id'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_session_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
